server:
  port: 3344
spring:
  application:
    name: cloud-config-center-dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/renkaige5/rkgspringcloud-config.git  #填写你自己的github路径
          search-paths:
            - rkgspringcloud-config
      label: master
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka
  
config:
  info: rkg-test
