spring:
  profiles:
    active:
    - test
---
spring:
  profiles: dev
  application:
    name: rkgspringcloud-config-dev
---
spring:
  profiles: test
  application:
    name: rkgspringcloud-config-test
